#
# Keybindings
#

hook global InsertChar j %{ try %{
    exec -draft hH <a-k>kj<ret> d
    exec <esc>
}}

map global normal <c-p> '   !  xsel --output --clipboard <ret>'
map global normal <c-P> '<a-!> xsel --output --clipboard <ret>'
map global normal <c-y> '<a-|> xsel --input --clipboard <ret>'

map global normal D xd
map global normal Y xy

set global tabstop 4                                                        
set global indentwidth 4

set global ui_options terminal_assistant=none

#
# Tab for both completion and indent
#

# hook global InsertCompletionShow .* %{
#   map window insert <tab> <c-n>
#   map window insert <s-tab> <c-p>
# }
# 
# hook global InsertCompletionHide .* %{
#   unmap window insert <tab> <c-n>
#   unmap window insert <s-tab> <c-p>
# }

#
# Colors
#
#colorscheme gruvbox
face global PrimarySelection black,blue+fg
face global SecondarySelection black,magenta+fg

face global PrimaryCursor   black,white+fg
face global SecondaryCursor magenta,white+fg

face global MenuInfo black,blue
face global MenuBackground black,blue
face global MenuForeground blue,black

#
# Plugins
#

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andeyost/plug.kak" noload config %{
    set-option global plug_always_ensure true
}

plug 'delapouite/kakoune-buffers' %{
    map global normal ^ q
    map global normal <a-^> Q
    map global normal q b
    map global normal Q B
    map global normal <a-q> <a-b>
    map global normal <a-Q> <a-B>
    map global normal b ': enter-buffers-mode<ret>' -docstring 'buffers'
    map global normal B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)'
    map global normal <a-b> ':info-buffers<ret>' -docstring 'buffers info'
    map global normal <a-B> ':info-buffers<ret>' -docstring 'buffers info'
}

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4
} config %{
    hook global WinSetOption filetype=(?!go).* expandtab
    hook global WinSetOption filetype=(go) smarttab
}

plug "alexherbo2/auto-pairs.kak"

plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{
    hook global WinSetOption filetype=(python) %{
        lsp-enable-window
        lsp-auto-hover-disable
        lsp-auto-signature-help-enable
        set-option window formatcmd "black --fast -q -"
        hook window BufWritePre .* format
    }
    
    hook global WinSetOption filetype=(jsx|tsx|typescript|javascript) %{
        lsp-enable-window
        lsp-auto-hover-disable
        lsp-auto-signature-help-enable
        # should use %opt{bufname} but can't figure out how to string interpolate
        set-option window formatcmd "prettier --stdin-filepath _.tsx"
        set-option window indentwidth 2
        hook window BufWritePre .* format
    }

    hook global WinSetOption filetype=(css) %{
        lsp-enable-window
        set-option window formatcmd "prettier --stdin-filepath _.css"
        hook window BufWritePre .* format
    }

    hook global WinSetOption filetype=(json) %{
        lsp-enable-window
        set-option window formatcmd "prettier --stdin-filepath _.json"
        hook window BufWritePre .* format
    }
    
    hook global WinSetOption filetype=(go) %{
        lsp-enable-window
        lsp-auto-hover-disable
        # lsp-auto-signature-help-enalbe
        hook window BufWritePre .* lsp-formatting-sync
    }

    map global user h :lsp-hover<ret> -docstring 'LSP hover' 
    map global user p :lsp-signature-help<ret> -docstring 'LSP signature'
    map global user g :enter-user-mode<space>lsp<ret> -docstring 'LSP'
}

plug 'delapouite/kakoune-text-objects' 

plug 'delapouite/kakoune-select-view' %{
    map global normal <a-%> ': select-view<ret>' -docstring 'select view'
    map global view s '<esc>: select-view<ret>' -docstring 'select view'
}

plug "occivink/kakoune-sudo-write"

plug "andreyorst/fzf.kak" config %{
    map global normal <c-f> '<esc>: fzf-mode<ret>' -docstring 'fzf mode'
}

plug "andreyorst/kaktree" config %{
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-highlighter buffer/matching
        remove-highlighter buffer/wrap
        remove-highlighter buffer/show-whitespaces
    }
    kaktree-enable
} defer kaktree %{
    set-option global kaktree_dir_icon_open  '▾ 🗁 '
    set-option global kaktree_dir_icon_close '▸ 🗀 '
    set-option global kaktree_file_icon      '⠀⠀🖺'
}

define-command ctrld -docstring 'does the ctrl-d thing' %{
    try %{
        # check if more than one character is selected
        execute-keys -draft <a-k>..+<ret>
        execute-keys *N
    } catch %{
        execute-keys <a-i>w*
    }
}
map global normal <c-e> <c-d>
map global normal <c-q> <c-u>
map global normal <c-d> :ctrld<ret>
