inherits = "monokai_pro"

# "ui.virtual.jump.single" = { fg = "#ff007c", modifiers = ["bold"] }
# "ui.virtual.jump.multi.first" = { fg = "#00dfff", modifiers = ["bold"] }
# "ui.virtual.jump.multi.rest" = "#2b8db3"
# "ui.virtual.jump.dim" = "base5"
"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold", "reversed"] }
