theme = "monokai_pro_custom"

[editor]
jump-label-alphabet = "asdfjklghqweruiopt;"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false


[keys.normal]
q = "move_prev_word_start"
Q = "move_prev_long_word_start"
"ret" = "keep_primary_selection"
g = { j = "goto_last_line", e = "goto_file_end", k = "goto_file_start" }
space = { q = ":buffer-close" }
D = ["extend_to_line_bounds", "delete_selection"]
"C-k" = ["collapse_selection", "insert_mode", "kill_to_line_end"]
"]" = { s = "select_next_sibling" }
"[" = { s = "select_prev_sibling" }
"C-g" = "page_down"
"C-f" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]
"A-m" = "save_selection"
"C-s" = "no_op"
"C-p" = "jump_backward"
"C-n" = "jump_forward"
"C-o" = "no_op"

[keys.select]
q = "extend_prev_word_start"
Q = "extend_prev_long_word_start"
"ret" = ["exit_select_mode", "keep_primary_selection"]
g = { j = "goto_last_line", e = "goto_file_end", k = "goto_file_start" }
space = { q = ":buffer-close" }
D = ["extend_to_line_bounds", "delete_selection"]
"C-k" = ["collapse_selection", "insert_mode", "kill_to_line_end"]
"]" = { s = "select_next_sibling" }
"[" = { s = "select_prev_sibling" }
"C-g" = ["exit_select_mode", "page_down"]
"C-f" = ["search_selection", "extend_search_next"]
"A-m" = "save_selection"
"C-s" = "no_op"
"C-p" = "jump_backward"
"C-n" = "jump_forward"
"C-o" = "no_op"

[keys.insert]
k = { j = "normal_mode" }
"C-space" = "completion"
"C-p" = "signature_help"
