theme = "monokai_pro_custom"

[editor.file-picker]
hidden = false

[keys.normal]
q = "move_prev_word_start"
Q = "move_prev_long_word_start"
"ret" = "keep_primary_selection"
g = { j = "goto_last_line", e = "goto_file_end", k = "goto_file_start" }
space = { q = ":buffer-close" }
D = ["extend_to_line_bounds", "delete_selection"]
"C-k" = ["collapse_selection", "insert_mode", "kill_to_line_end"]

[keys.select]
q = "extend_prev_word_start"
Q = "extend_prev_long_word_start"
"ret" = ["exit_select_mode", "keep_primary_selection"]
g = { j = "goto_last_line", e = "goto_file_end", k = "goto_file_start" }
space = { q = ":buffer-close" }
D = ["extend_to_line_bounds", "delete_selection"]
"C-k" = ["collapse_selection", "insert_mode", "kill_to_line_end"]

[keys.insert]
k = { j = "normal_mode" }

