[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "cspell"]

[[language]]
name = "go"
language-servers = ["gopls", "cspell"]

[[language]]
name = "markdown"
language-servers = [ "marksman", "cspell" ]
